 
version: '3'

services:

  rabbit:
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_HOST: "microsservicos-aula-1_rabbit_1"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
      RABBITMQ_DLX: "dlx"
    ports:
      - "15672:15672"
      - "5672:5672"
  microservico1:
    image: andressandrade/desafio3-avancadev-1:latest
    ports:
      - 9090:9090
  microservico2:
    depends_on:
      - "rabbit"
    image: andressandrade/desafio3-avancadev-2:latest
    ports:
      - 9091:9091
    restart: on-failure
  microservico3:
    image: andressandrade/desafio3-avancadev-3:latest
    ports:
      - 9092:9092
  microservico4:
    image: andressandrade/desafio3-avancadev-4:latest
    ports:
      - 3333:3333