version: '3'

services:

  rabbit:
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
  microsservicoa:
    image: andressandrade/desafio3-avancadev-a
    ports:
      - "9090:9090"
  microsservicob:
    depends_on:
      - "rabbit"
    image: andressandrade/desafio3-avancadev-b
    restart: on-failure
  microsservicoc:
    image: andressandrade/desafio3-avancadev-c
    ports:
      - 9092